spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/dental?sslmode=disable
  username: postgres
  password: postgres
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  properties:
   hibernates:
    format-sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
 liquibase:
  enabled: false
   
scheduling:
 enabled: true
  
app:
 jwt:
  secretKey: supercalifragilisticexpialidocioussecretkeyhere
  token-prefix: Bearer
  token-expiration-after-days: 1

