package com.clinic.dental.model.appointment.enums;

public enum AppointmentType {
	COMPLETE,
	FILLINGS,
	COSMETIC,
	IMPLANTS,
	ORTHODONTICS,
	PREVENTATIVE_CARE,
	PERIODONTAL_THERAPY,
	NUTRITIONAL_COUNSELING,
	ROOT_CANALS,
	GENERAL;
}
